### ISSUE TITLE
stw_meta: source to sources

### ISSUE THREAD

**Issue by ijlyttle** [uncoast-unconf/steward#67]
To conform with the [table-schema](http://frictionlessdata.io/specs/tabular-data-resource) used by csvy - #65:

```yaml
sources:
  - title: ''
    path: ''
    email: ''
  - title: ''
    path: ''
    email: ''
```

This means we will need to modify the outputs for gt and roxygen
